<?php

/**
 * @file
 * Contains iai_aquifer.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function iai_aquifer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the iai_aquifer module.
    case 'help.page.iai_aquifer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module is supposed to store configuration for aquifers') . '</p>';
      return $output;

    default:
  }
}
